### ISSUE TITLE
Value of type 'UIView' has no member 'fadeIn'

### ISSUE THREAD

**Issue by shahab8020** [keithito/SimpleAnimation#17]
Hello.

The package is correctly installed and projects runs without error. But it seems that xcode doesn't recognize the functions and gives the following error for every function (like fadeIn):

Value of type 'UIView' has no member 'fadeIn'

What is the problem? I'm using Swift 3.

Thanks.

**Comment by keithito** [comment]
Have you tried restarting Xcode? Sometimes it doesn't pick up new dependencies properly after installing pods.

**Comment by keithito** [comment]
Closing inactive issues. Please feel free to re-open if you have any updates. Thanks!
